@echo off
REM verify_noir.bat
REM Windows batch version of verify_noir.sh
REM Verifies ZK proofs generated by Noir circuits

setlocal EnableDelayedExpansion

REM Script configuration
set "SCRIPT_DIR=%~dp0"
set "PROJECT_ROOT=%SCRIPT_DIR%.."
set "CIRCUITS_DIR=%PROJECT_ROOT%\zk\noir-circuits"
set "PROOFS_DIR=%PROJECT_ROOT%\zk\proofs"
set "VERIFIERS_DIR=%PROJECT_ROOT%\zk\verifiers"

echo ================================================
echo 🔍 DVote Noir Proof Verifier (Windows)
echo ================================================

REM Parse arguments
if "%1"=="" goto show_usage
if "%1"=="--help" goto show_usage

set "CIRCUIT_NAME=%1"
set "PROOF_FILE="
set "EXPORT_VK=false"

REM Parse additional options
shift
:parse_options
if "%1"=="" goto options_done
if "%1"=="--proof-file" (
    set "PROOF_FILE=%2"
    shift
    shift
    goto parse_options
)
if "%1"=="--export-vk" (
    set "EXPORT_VK=true"
    shift
    goto parse_options
)
shift
goto parse_options
:options_done

REM Validate circuit name
set "VALID_CIRCUIT=false"
for %%c in (age_proof citizenship_proof attribute_proof) do (
    if "%CIRCUIT_NAME%"=="%%c" set "VALID_CIRCUIT=true"
)

if "%VALID_CIRCUIT%"=="false" (
    echo ❌ Unknown circuit: %CIRCUIT_NAME%
    echo.
    goto show_usage
)

echo Checking dependencies...

REM Check if nargo is available
if exist "%CIRCUITS_DIR%\nargo.bat" (
    echo ✅ Found nargo.bat
) else if exist "%CIRCUITS_DIR%\nargo.js" (
    echo ✅ Found nargo.js
) else (
    echo ❌ nargo not found. Please build circuits first.
    exit /b 1
)

REM Check Node.js
where node >nul 2>nul
if %errorlevel% neq 0 (
    echo ❌ Node.js is required for verification
    exit /b 1
) else (
    echo ✅ Node.js found
)

echo Starting proof verification for %CIRCUIT_NAME%...

REM Determine proof file path
if "%PROOF_FILE%" neq "" (
    set "ACTUAL_PROOF_FILE=%PROOF_FILE%"
) else (
    set "ACTUAL_PROOF_FILE=%PROOFS_DIR%\%CIRCUIT_NAME%\proof.json"
)

REM Check if proof file exists
if not exist "%ACTUAL_PROOF_FILE%" (
    echo ❌ Proof file not found: %ACTUAL_PROOF_FILE%
    echo Generate a proof first using: .\scripts\prove_noir.bat %CIRCUIT_NAME%
    exit /b 1
)

echo ✅ Found proof file: %ACTUAL_PROOF_FILE%

REM Create verifier directory
if not exist "%VERIFIERS_DIR%\%CIRCUIT_NAME%" mkdir "%VERIFIERS_DIR%\%CIRCUIT_NAME%"

REM Use the verification helper script
cd /d "%PROJECT_ROOT%"
echo Running proof verification...

REM Prepare arguments for the helper
if "%EXPORT_VK%"=="true" (
    if "%PROOF_FILE%" neq "" (
        node "%SCRIPT_DIR%\verify_helper.js" "%CIRCUIT_NAME%" "%PROOF_FILE%" "--export-vk"
    ) else (
        node "%SCRIPT_DIR%\verify_helper.js" "%CIRCUIT_NAME%" "" "--export-vk"
    )
) else (
    if "%PROOF_FILE%" neq "" (
        node "%SCRIPT_DIR%\verify_helper.js" "%CIRCUIT_NAME%" "%PROOF_FILE%"
    ) else (
        node "%SCRIPT_DIR%\verify_helper.js" "%CIRCUIT_NAME%"
    )
)
if %errorlevel% equ 0 (
    echo ✅ Verification completed successfully
    
    REM Display verification summary
    echo.
    echo === Verification Summary for %CIRCUIT_NAME% ===
    
    if exist "%PROOFS_DIR%\%CIRCUIT_NAME%\proof.json" (
        echo 📄 Proof file: %PROOFS_DIR%\%CIRCUIT_NAME%\proof.json
    )
    
    if exist "%VERIFIERS_DIR%\%CIRCUIT_NAME%\verification_result.json" (
        echo ✅ Verification result: Available
    )
    
    if "%EXPORT_VK%"=="true" (
        if exist "%VERIFIERS_DIR%\%CIRCUIT_NAME%\verification_key.json" (
            echo 🔑 Verification key: Exported
        )
    ) else (
        echo 🔑 Verification key: Not generated (use --export-vk)
    )
    
) else (
    echo ❌ Verification failed
    exit /b 1
)

echo.
echo ✅ Verification process completed!
echo Verification results saved to: %VERIFIERS_DIR%\%CIRCUIT_NAME%\
goto end

:show_usage
echo Usage: %0 ^<circuit_name^> [options]
echo.
echo Arguments:
echo   circuit_name              Circuit to verify proof for (age_proof, citizenship_proof, attribute_proof)
echo.
echo Options:
echo   --proof-file ^<file^>       Use custom proof file (default: zk/proofs/{circuit}/proof.json)
echo   --export-vk              Extract and export verification key
echo   --help                   Show this help message
echo.
echo Examples:
echo   %0 age_proof                          # Verify proof with default file
echo   %0 age_proof --export-vk              # Verify and export verification key
echo   %0 citizenship_proof --proof-file my_proof.json
echo.
echo Available circuits:
echo   - age_proof
echo   - citizenship_proof
echo   - attribute_proof

:end
endlocal